language: ruby
rvm: 2.4.1
env: RAILS_ENV=test
script:
  - bundle exec rspec spec/
addons:
  postgresql: "9.4"
before_script:
  - cp test/dummy/config/database.travis.yml test/dummy/config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

